# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    product_status.storage:
        class: WellCommerce\Bundle\ProductStatusBundle\Storage\ProductStatusStorage

    product_status.request_param_converter:
        class: WellCommerce\Bundle\ProductStatusBundle\Request\ParamConverter\ProductStatusParamConverter
        tags:
            - { name: request.param_converter, converter: product, priority: 0 }
        arguments: ['@product_status.repository', id, [WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatus, WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatusInterface]]

    product_status.transformer:
        class: WellCommerce\Bundle\ProductStatusBundle\DataSet\Transformer\ProductStatusTransformer
        tags:
            - { name: dataset.transformer, alias: product_status }

    twig.extension.product_status:
        class: WellCommerce\Bundle\ProductStatusBundle\Twig\Extension\ProductStatusExtension
        tags:
            - { name: twig.extension }
        arguments: ['@product_status.dataset.front', '@product_status.repository']
