WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatus:
    fields:
        id:
            groups:
                - default
                - product_status
        symbol:
            groups:
                - default
                - product_status
    associations:
        translations:
            groups:
                - product_status
